// Top ~350 US cities by population + notable cities, covering all 50 states + DC
// Format: "City, ST" for easy display and parsing
export const US_CITIES: string[] = [
  "New York, NY", "Los Angeles, CA", "Chicago, IL", "Houston, TX", "Phoenix, AZ",
  "Philadelphia, PA", "San Antonio, TX", "San Diego, CA", "Dallas, TX", "San Jose, CA",
  "Austin, TX", "Jacksonville, FL", "Fort Worth, TX", "Columbus, OH", "Charlotte, NC",
  "Indianapolis, IN", "San Francisco, CA", "Seattle, WA", "Denver, CO", "Washington, DC",
  "Nashville, TN", "Oklahoma City, OK", "El Paso, TX", "Boston, MA", "Portland, OR",
  "Las Vegas, NV", "Memphis, TN", "Louisville, KY", "Baltimore, MD", "Milwaukee, WI",
  "Albuquerque, NM", "Tucson, AZ", "Fresno, CA", "Mesa, AZ", "Sacramento, CA",
  "Atlanta, GA", "Kansas City, MO", "Colorado Springs, CO", "Omaha, NE", "Raleigh, NC",
  "Virginia Beach, VA", "Long Beach, CA", "Miami, FL", "Oakland, CA", "Minneapolis, MN",
  "Tulsa, OK", "Tampa, FL", "Arlington, TX", "New Orleans, LA", "Wichita, KS",
  "Cleveland, OH", "Bakersfield, CA", "Aurora, CO", "Anaheim, CA", "Honolulu, HI",
  "Santa Ana, CA", "Riverside, CA", "Corpus Christi, TX", "Lexington, KY", "Stockton, CA",
  "Henderson, NV", "Saint Paul, MN", "Pittsburgh, PA", "Cincinnati, OH", "Anchorage, AK",
  "Greensboro, NC", "Plano, TX", "Lincoln, NE", "Orlando, FL", "Irvine, CA",
  "Newark, NJ", "Toledo, OH", "Durham, NC", "Chula Vista, CA", "Fort Wayne, IN",
  "Jersey City, NJ", "St. Petersburg, FL", "Laredo, TX", "Madison, WI", "Chandler, AZ",
  "Buffalo, NY", "Lubbock, TX", "Scottsdale, AZ", "Reno, NV", "Glendale, AZ",
  "Gilbert, AZ", "Winston-Salem, NC", "North Las Vegas, NV", "Norfolk, VA", "Chesapeake, VA",
  "Garland, TX", "Irving, TX", "Hialeah, FL", "Fremont, CA", "Boise, ID",
  "Richmond, VA", "Baton Rouge, LA", "Spokane, WA", "Des Moines, IA", "Tacoma, WA",
  "San Bernardino, CA", "Modesto, CA", "Fontana, CA", "Moreno Valley, CA", "Santa Clarita, CA",
  "Fayetteville, NC", "Birmingham, AL", "Oxnard, CA", "Rochester, NY", "Port St. Lucie, FL",
  "Grand Rapids, MI", "Huntsville, AL", "Salt Lake City, UT", "Frisco, TX", "Yonkers, NY",
  "Amarillo, TX", "Glendale, CA", "Huntington Beach, CA", "McKinney, TX", "Montgomery, AL",
  "Augusta, GA", "Aurora, IL", "Akron, OH", "Little Rock, AR", "Tempe, AZ",
  "Columbus, GA", "Overland Park, KS", "Grand Prairie, TX", "Tallahassee, FL", "Cape Coral, FL",
  "Mobile, AL", "Knoxville, TN", "Shreveport, LA", "Worcester, MA", "Ontario, CA",
  "Vancouver, WA", "Sioux Falls, SD", "Chattanooga, TN", "Brownsville, TX", "Fort Lauderdale, FL",
  "Providence, RI", "Newport News, VA", "Rancho Cucamonga, CA", "Santa Rosa, CA", "Peoria, AZ",
  "Oceanside, CA", "Elk Grove, CA", "Salem, OR", "Pembroke Pines, FL", "Eugene, OR",
  "Garden Grove, CA", "Cary, NC", "Corona, CA", "Springfield, MO", "Fort Collins, CO",
  "Jackson, MS", "Alexandria, VA", "Hayward, CA", "Lancaster, CA", "Salinas, CA",
  "Palmdale, CA", "Hollywood, FL", "Springfield, MA", "Macon, GA", "Kansas City, KS",
  "Sunnyvale, CA", "Pomona, CA", "Killeen, TX", "Escondido, CA", "Pasadena, TX",
  "Naperville, IL", "Bellevue, WA", "Joliet, IL", "Murfreesboro, TN", "Midland, TX",
  "Rockford, IL", "Paterson, NJ", "Savannah, GA", "Bridgeport, CT", "Torrance, CA",
  "McAllen, TX", "Syracuse, NY", "Surprise, AZ", "Denton, TX", "Roseville, CA",
  "Thornton, CO", "Miramar, FL", "Pasadena, CA", "Mesquite, TX", "Olathe, KS",
  "Dayton, OH", "Charleston, SC", "Gainesville, FL", "Waco, TX", "West Valley City, UT",
  "Visalia, CA", "Columbia, SC", "Sterling Heights, MI", "New Haven, CT", "Carrollton, TX",
  "Cedar Rapids, IA", "Round Rock, TX", "Stamford, CT", "Norman, OK", "Columbia, MO",
  "Fargo, ND", "Concord, CA", "Meridian, ID", "Topeka, KS", "Hartford, CT",
  "Wilmington, NC", "Lakewood, CO", "West Palm Beach, FL", "Elizabeth, NJ", "Victorville, CA",
  "Provo, UT", "Athens, GA", "Pearland, TX", "Vallejo, CA", "Ann Arbor, MI",
  "Berkeley, CA", "El Monte, CA", "Downey, CA", "Costa Mesa, CA", "Inglewood, CA",
  "Miami Gardens, FL", "Arvada, CO", "Carlsbad, CA", "Westminster, CO", "Rochester, MN",
  "Odessa, TX", "Manchester, NH", "Elgin, IL", "West Jordan, UT", "Palm Bay, FL",
  "Clearwater, FL", "Beaumont, TX", "Independence, MO", "Temecula, CA", "Lansing, MI",
  "Lafayette, LA", "Billings, MT", "Pueblo, CO", "Tuscaloosa, AL", "Evansville, IN",
  "North Charleston, SC", "Broken Arrow, OK", "Palm Coast, FL", "Pompano Beach, FL",
  "Lewisville, TX", "Edmond, OK", "Springfield, IL", "Sandy Springs, GA", "College Station, TX",
  "Tyler, TX", "Davie, FL", "Lakeland, FL", "Boulder, CO", "Allen, TX",
  "West Covina, CA", "Sparks, NV", "Wichita Falls, TX", "Green Bay, WI", "San Mateo, CA",
  "Norwalk, CA", "League City, TX", "South Bend, IN", "Rio Rancho, NM", "Goodyear, AZ",
  "High Point, NC", "Davenport, IA", "Fishers, IN", "Lee's Summit, MO", "O'Fallon, MO",
  "Largo, FL", "Daly City, CA", "Kennewick, WA", "Lawton, OK", "Longmont, CO",
  "Roanoke, VA", "Kenosha, WI", "Sandy, UT", "Lynchburg, VA", "Tuscaloosa, AL",
  "Newport Beach, CA", "Orem, UT", "Flower Mound, TX", "Champaign, IL", "New Braunfels, TX",
  "Duluth, MN", "Rapid City, SD", "Cheyenne, WY", "Casper, WY", "Burlington, VT",
  "Montpelier, VT", "Juneau, AK", "Fairbanks, AK", "Bismarck, ND", "Pierre, SD",
  "Helena, MT", "Great Falls, MT", "Missoula, MT", "Bangor, ME", "Portland, ME",
  "Dover, DE", "Wilmington, DE", "Charleston, WV", "Huntington, WV", "Morgantown, WV",
  "Pensacola, FL", "Sarasota, FL", "Naples, FL", "Key West, FL", "Daytona Beach, FL",
  "Asheville, NC", "Savannah, GA", "Charleston, SC", "Myrtle Beach, SC", "Greenville, SC",
  "Santa Fe, NM", "Las Cruces, NM", "Flagstaff, AZ", "Sedona, AZ", "Bend, OR",
  "Bozeman, MT", "Park City, UT", "Jackson, WY", "Aspen, CO", "Steamboat Springs, CO",
  "Napa, CA", "Santa Barbara, CA", "San Luis Obispo, CA", "Monterey, CA", "Maui, HI",
];
